# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Papa Game Dev
description: Paternidad y Videojuegos
github_username: papagamedev
lang: es

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

header_pages:
  - articulos.md
  - proyectos.md
  - contacto.md

remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/papagamedev" }
    - { platform: twitter, user_url: "https://twitter.com/papagamedev/"}
    - { platform: instagram, user_url: "https://instagram.com/papagamedev/"}

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
exclude:
  - Gemfile.lock

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
