# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Papa Game Dev
description: Paternidad y Videojuegos
logo: /images/papagamedev_logo_web.png
url: "https://papagame.dev"
github_username: papagamedev
lang: es

comments_enabled: true

twitter:
  username: papagamedev
  card: summary

google_analytics: G-DTFYGQX4WT

permalink: /:year/:month/:title:output_ext

header_pages:
  - category/articles-es.md
  - category/articles-en.md
  - category/projects-es.md
  - category/projects-en.md
  - search-es.md
  - search-en.md
  - contacto.md
  - contact.md

date_format: "%b %-d, %Y"
datetime_format: "%b %-d, %Y - %H:%M"

backend:
  base_url_dev: http://localhost:7071/api
  base_url_prod: https://papagamedevsite.azurewebsites.net/api
  comment_api: /comment
  contact_api: /contact

reCaptcha:
  siteKey: 6LeaCwsTAAAAAC1B4rTP9IbD9O4WACfBXbbpWsdv

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments_enabled: true
      featured: false

remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/papagamedev" }
    - { platform: twitter, user_url: "https://twitter.com/papagamedev/"}
    - { platform: instagram, user_url: "https://instagram.com/papagamedev/"}
    - { platform: facebook, user_url: "https://facebook.com/papagamedev/"}

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-redirect-from
exclude:
  - Gemfile.lock

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
